apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xgsk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xgsk
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xgsk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xgsk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xgsk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oosi-tenant/rhtap-demo-app/hacbs-test-project-xgsk@sha256:1d9027f028560a1e4d71f79d8adbab5fbcc12ffb2cb0ef0870ccd2a73f09d444
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
