apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xgsk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-oosi-tenant/rhtap-demo-app/hacbs-test-project-xgsk@sha256:1d9027f028560a1e4d71f79d8adbab5fbcc12ffb2cb0ef0870ccd2a73f09d444
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
